name: build

on:
  push:
    branches: [main]
    tags:
      - '*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      - env:
          CRX_PRIVATE_KEY: ${{ secrets.CRX_PRIVATE_KEY }}
        run: |
          echo "$CRX_PRIVATE_KEY" > dist.pem
          chmod 600 dist.pem
          ./buildcrx.sh -d dist -p dist.pem -o .
          zip -r magic-copy.zip dist
      - name: Upload zip
        uses: actions/upload-artifact@v2
        with:
          name: magic-copy
          path: dist
      - name: Upload crx
        uses: actions/upload-artifact@v2
        with:
          name: magic-copy.crx
          path: dist.crx
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: magic-copy.zip
